AWSTemplateFormatVersion: '2010-09-09'
Description: SmartCare - ECR repositories for microservice container images

Parameters:
  Environment:
    Type: String
    Default: dev

Resources:
  AppWebRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub smartcare-app-web-${Environment}
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {"rules":[{"rulePriority":1,"selection":{"tagStatus":"untagged","countType":"sinceImagePushed","countUnit":"days","countNumber":7},"action":{"type":"expire"}},{"rulePriority":2,"selection":{"tagStatus":"tagged","tagPrefixList":["v"],"countType":"imageCountMoreThan","countNumber":10},"action":{"type":"expire"}}]}
      Tags:
        - Key: Project
          Value: SmartCare
        - Key: Environment
          Value: !Ref Environment
        - Key: Component
          Value: ECR

  AppMessageBrokerRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub smartcare-app-message-broker-${Environment}
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {"rules":[{"rulePriority":1,"selection":{"tagStatus":"untagged","countType":"sinceImagePushed","countUnit":"days","countNumber":7},"action":{"type":"expire"}},{"rulePriority":2,"selection":{"tagStatus":"tagged","tagPrefixList":["v"],"countType":"imageCountMoreThan","countNumber":10},"action":{"type":"expire"}}]}
      Tags:
        - Key: Project
          Value: SmartCare
        - Key: Environment
          Value: !Ref Environment
        - Key: Component
          Value: ECR

Outputs:
  AppWebRepoUri:
    Value: !GetAtt AppWebRepo.RepositoryUri
    Export:
      Name: !Sub smartcare-${Environment}-ecr-app-web
  AppMessageBrokerRepoUri:
    Value: !GetAtt AppMessageBrokerRepo.RepositoryUri
    Export:
      Name: !Sub smartcare-${Environment}-ecr-app-message-broker
