import { Routes } from '@angular/router';
import { DashboardComponent } from './pages/dashboard/dashboard.component';
import { AgentsComponent } from './pages/agents/agents.component';
import { ScenariosComponent } from './pages/scenarios/scenarios.component';
import { AnalyticsComponent } from './pages/analytics/analytics.component';
import { DatasetsComponent } from './pages/datasets/datasets.component';
import { DatasetInstancesComponent } from './pages/dataset-instances/dataset-instances.component';
import { DatasetInstanceViewComponent } from './pages/dataset-instance-view/dataset-instance-view.component';
import { DigitalTwinComponent } from './pages/digital-twin/digital-twin.component';
import { MessagesTopicsComponent } from './pages/messages-topics/messages-topics.component';
import { MessagesDetailComponent } from './pages/messages-detail/messages-detail.component';
import { AuditComponent } from './pages/audit/audit.component';
import { SecretsComponent } from './pages/secrets/secrets.component';
import { SecretEditComponent } from './pages/secret-edit/secret-edit.component';
import { SettingsComponent } from './pages/settings/settings.component';

export const routes: Routes = [
  { path: '', component: DashboardComponent },
  { path: 'agents', component: AgentsComponent },
  { path: 'scenarios', component: ScenariosComponent },
  { path: 'analytics', component: AnalyticsComponent },
  { path: 'datasets', component: DatasetsComponent },
  { path: 'dataset-instances', component: DatasetInstancesComponent },
  { path: 'dataset-instances/:id/view', component: DatasetInstanceViewComponent },
  { path: 'digital-twin', component: DigitalTwinComponent },
  { path: 'secrets', component: SecretsComponent },
  { path: 'secrets/:id/edit', component: SecretEditComponent },
  { path: 'messages', component: MessagesTopicsComponent },
  { path: 'messages/:topicName', component: MessagesDetailComponent },
  { path: 'audit', component: AuditComponent },
  { path: 'settings', component: SettingsComponent },
  { path: '**', redirectTo: '' }
];
