name: "AWS-002: Create S3 Bucket"
on:
  workflow_dispatch:
  workflow_call:

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AGENTIC_SCS_CLAIMS_PROC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AGENTIC_SCS_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AGENTIC_SCS_AWS_REGION || 'us-east-1' }}
      - name: Deploy S3 Bucket
        run: |
          aws cloudformation deploy \
            --stack-name "smartcare-s3-bucket" \
            --template-file infra/cfn-s3-bucket.yaml \
            --no-fail-on-empty-changeset
