name: "AWS-003: Destroy SNS Topics"
on:
  workflow_dispatch:
  workflow_call:
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AGENTIC_SCS_CLAIMS_PROC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AGENTIC_SCS_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AGENTIC_SCS_AWS_REGION || 'us-east-1' }}
      - name: Destroy Stack
        run: |
          aws cloudformation delete-stack --stack-name "smartcare-sns-topics"
          aws cloudformation wait stack-delete-complete --stack-name "smartcare-sns-topics" || true
