name: "AWS-002: Destroy S3 Bucket"
on:
  workflow_dispatch:
  workflow_call:
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}
      - name: Empty S3 Bucket
        run: |
          aws s3 rm s3://smartcare-datasets-*/ --recursive || true
      - name: Destroy Stack
        run: |
          aws cloudformation delete-stack --stack-name "smartcare-s3-bucket"
          aws cloudformation wait stack-delete-complete --stack-name "smartcare-s3-bucket" || true
